# Generated by Django 4.1.6 on 2023-04-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='stepphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='steps/photo/'),
        ),
        migrations.AlterField(
            model_name='stepvideo',
            name='video',
            field=models.FileField(upload_to='steps/videos/'),
        ),
    ]
