# Generated by Django 4.1.6 on 2023-04-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_favorite_recipe_alter_favorite_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingss', to='recipes.recipe'),
        ),
    ]
